baseURL = "http://soup.rocks"
languageCode = "en-us"
title = "THIS SOUP TASTES DELICIOUS"
theme = "harbor"
author = "Letchik Bulochkin"
paginate = 3
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-41189174-2"

[Author]
  name = "Letchik Bulochkin"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"